- name: Install isc-dhcp-server on gate machine
  hosts: gate
  remote_user: root
  become: true
  
  tasks:
    - name: Installing needed packages
      ansible.builtin.apt:
        name: isc-dhcp-server
        state: present
        update_cache: yes

    - name: Set right adapter for dhcp 
      ansible.builtin.replace:
        path: /etc/default/isc-dhcp-server
        regexp: ^INTERFACESv4=".*"$
        replace: 'INTERFACESv4="{{ adapter_1 }}"'

    - name: Make dhcp-server configurations
      template:
        src: templates/dhcp/dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: "0644"

    - name: Create dhcpd pid file
      ansible.builtin.shell: |
        dhcpd -t
    
    - name: Restart isc-dhcp-server.service
      ansible.builtin.service:
        name: isc-dhcp-server
        state: restarted



