- name: Setup bind9 DNS server on server machine
  hosts: server
  remote_user: root
  become: yes

  tasks:
    - name: Install dns and bind9 utils
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - dnsutils
        - bind9
        - bind9-doc

    - name: Change /etc/resolv.conf
      template:
        src: templates/dns/resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: "0644"

    - name: Make /etc/resolv.conf immutable
      ansible.builtin.command: chattr +i /etc/resolv.conf

    - name: Configure /etc/bind/named.conf.options
      copy:
        src: files/named.conf.options
        dest: /etc/bind/named.conf.options
        force: yes

    - name: Configure straight DNS zone
      template:
        src: templates/dns/example.{{ item }}.j2
        dest: /etc/bind/example{{ N }}.{{ item }}
        owner: root
        group: root
        mode: "0644"
      loop:
        - com
        - rev

    - name: Setup zones in /etc/bind/named/conf.local
      template:
        src: templates/dns/named.conf.local.j2
        dest: /etc/bind/named.conf.local
        owner: root
        group: root
        mode: "0644"

    - name: Reload all zones
      ansible.builtin.command: rndc reload

    - name: Restart bind9 & networking services
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - bind9
        - networking
        - NetworkManager



- name: Setup DNS on gate
  hosts: gate
  remote_user: root
  become: yes

  tasks:
    - name: Change /etc/resolv.conf
      template:
        src: templates/dns/resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: "0644"

    - name: Make /etc/resolv.conf immutable
      ansible.builtin.command: chattr +i /etc/resolv.conf

    - name: Restart networks services
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - networking
        - NetworkManager
